name: Build All Platforms

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-web:
    name: Build Web (JS + WasmJS)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - uses: gradle/actions/setup-gradle@v4

      - name: Build JS production bundle
        run: ./gradlew :composeApp:jsBrowserProductionWebpack

      - name: Build WasmJS production bundle
        run: ./gradlew :composeApp:wasmJsBrowserProductionWebpack

      - name: Upload JS artifact
        uses: actions/upload-artifact@v4
        with:
          name: web-js
          path: composeApp/build/dist/js/productionExecutable/

      - name: Upload WasmJS artifact
        uses: actions/upload-artifact@v4
        with:
          name: web-wasmjs
          path: composeApp/build/dist/wasmJs/productionExecutable/

  build-android:
    name: Build Android
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - uses: gradle/actions/setup-gradle@v4

      - name: Build release APK
        run: ./gradlew :androidApp:assembleRelease

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: android-apk
          path: androidApp/build/outputs/apk/release/*.apk

  build-windows:
    name: Build Windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - uses: gradle/actions/setup-gradle@v4

      - name: Build MSI installer
        run: ./gradlew :composeApp:packageMsi

      - name: Upload MSI
        uses: actions/upload-artifact@v4
        with:
          name: windows-msi
          path: composeApp/build/compose/binaries/main/msi/*.msi

  build-macos:
    name: Build macOS
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - uses: gradle/actions/setup-gradle@v4

      - name: Build DMG
        run: ./gradlew :composeApp:packageDmg

      - name: Upload DMG
        uses: actions/upload-artifact@v4
        with:
          name: macos-dmg
          path: composeApp/build/compose/binaries/main/dmg/*.dmg

  build-ios:
    name: Build iOS
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - uses: gradle/actions/setup-gradle@v4

      - name: Build KMP framework
        run: ./gradlew :composeApp:linkReleaseFrameworkIosArm64

      - name: Build iOS archive
        run: |
          xcodebuild archive \
            -project iosApp/iosApp.xcodeproj \
            -scheme iosApp \
            -configuration Release \
            -destination 'generic/platform=iOS' \
            -archivePath build/iosApp.xcarchive \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO

      - name: Upload iOS archive
        uses: actions/upload-artifact@v4
        with:
          name: ios-archive
          path: build/iosApp.xcarchive
